name: Python CI

# TODO: 正しく動くようになったらcronの定期実行にする
on: [push]

jobs:
  auto-insert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # 一通りinstallしたイメージを作成してそれを使うようにしたい
      # ChromeとPythonの依存関係をDockerfileに記載したい（ジョブの実行時はイメージをpull、pythonのコードをcopyして実行の流れを想定）
      - name: Install Chrome
        run: |
          sudo apt -y update
          sudo apt install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt install -y -f

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install supabase
          pip install selenium
          pip install webdriver-manager
          pip install beautifulsoup4
          pip install psycopg2-binary

      - name: Insert data to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        run: python auto_insert.py
